# Generated by Django 5.1.4 on 2025-02-09 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('income', 'Приход'), ('expense', 'Разход')], max_length=10)),
                ('category', models.CharField(choices=[('food', 'Храна'), ('transport', 'Транспорт'), ('entertainment', 'Забавления'), ('bills', 'Сметки'), ('health', 'Здраве'), ('rent', 'Наем'), ('dept', 'Заем'), ('salary', 'Заплата'), ('other', 'Други')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
