# Generated by Django 5.1.4 on 2025-02-07 19:01

import calendars.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0003_remove_event_users_alter_event_time_calendar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='calendar',
            field=models.ForeignKey(blank=True, default=calendars.models.get_default_calendar, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='calendars.calendar'),
        ),
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
