# Generated by Django 5.1.4 on 2025-02-08 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0005_event_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='join_code',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
