# Generated by Django 4.1 on 2025-02-12 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='category',
            field=models.CharField(blank=True, choices=[('work', 'Работа'), ('education', 'Образование'), ('ideas', 'Идеи'), ('travel', 'Пътуване'), ('health', 'Здраве'), ('hobbies', 'Хобита'), ('recipes', 'Рецепти'), ('personal', 'Лични бележки')], max_length=50, null=True),
        ),
    ]
