# Generated by Django 5.1.4 on 2025-02-04 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_todoitem_todo_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='todo_list',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tasks.todolist'),
        ),
    ]
