# Generated by Django 5.1.4 on 2025-02-06 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_todoitem_todo_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='status',
        ),
    ]
