# Generated by Django 5.1.4 on 2025-02-06 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_remove_todoitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='join_code',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
